version: "3"
services:
  frontend:
    working_dir: /home/node/app
    build: .
    ports:
      - 3500:3500
    volumes:
      - ./:/home/node/app
    command: "yarn frontend:start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose:
      - 3500
